// The writing. One string per piece. Plain text, 1–3 sentences.
// Order here does not matter — selection.js shuffles deterministically.
// To add more: append to the array. Nothing else to change.

export const PIECES = [
  "Yesterday is a story you tell yourself. Tomorrow is a story you tell yourself. You are only ever standing in the sentence you're speaking now.",
  "The future never arrives. By the time it does, it's this — and this is the thing you keep deferring.",
  "You have never once been in the future. Not for a second. Sit with that.",
  "Everything you have ever done, you did now.",
  "The day you're waiting for is made of days like this one.",
  "Nostalgia is rent you pay on a house you no longer live in.",
  "You rehearsed that conversation forty times. It happened once, differently, and you missed most of it preparing.",
  "The plan is not the life. The plan is a sketch you keep redrawing instead of going outside.",
  "Somewhere you decided life would begin once a condition was met. The condition keeps moving. Life didn't wait.",
  "You are not behind. There is no schedule. There is a day, and you are in it.",
  "Grief pulls backward, worry pulls forward, and the one being pulled is standing right here the whole time.",
  "This mood is weather. Stand in it; it moves.",
  "The people you love are in a version of themselves right now that won't exist next year. Look at this one.",
  "You keep arriving somewhere and immediately leaving for the next place. Try staying for the length of one breath.",
  "Boredom is usually just not having looked closely enough yet.",
  "Your attention is your life. Whatever it rests on, that is what you are living.",
  "The past is not where you left it. Every time you go back you rearrange the furniture.",
  "You are spending a day. Not rehearsing one. This is the one being spent.",
  "\"Later\" is where you put the things you're afraid to do now.",
  "The someday list is a graveyard with good intentions for headstones.",
  "You will not read it later. You will be a different person later, with a later of their own.",
  "Waiting is not nothing. It's most of a life — the commute, the line, the hold music. That's the material.",
  "Your body has never been anywhere but here. It doesn't know how to time-travel. Follow it back.",
  "Anticipation ate the trip before you packed. Leave some of it for the actual road.",
  "The next thing will also have a next thing. There is no final thing you arrive at and rest.",
  "You keep sending bills to your future self like he's a stranger who owes you. He's you, and he's tired.",
  "One day this will be the past you ache for. It's happening at normal speed right now.",
  "Regret is a way of staying. Make the amends and come back.",
  "Checking the time is checking for the exit. Where are you going that's better than the room you're in?",
  "Half of listening is just not loading your reply while the other person is still talking.",
  "Nothing has ever happened in the future. Every event in history occurred at a moment someone was calling now.",
  "You don't have to earn this hour. It was given. Spend it awake.",
  "The mind offers you the past and the future because it is frightened of the present — the one place it can't control anything.",
  "If you are always getting ready to live, that is the life: getting ready.",
  "This is not the part before the good part. There is no part before. This is the part.",
  "You remember the highlights and forget the ten thousand ordinary Tuesdays that were also your life.",
  "Put the phone down and the room is still here. It was the whole time.",
  "The thing you're worried about is a film. You wrote it, you're screening it, and it may never be released.",
  "Impermanence isn't the tragedy. It's the reason any of this counts.",
  "You can't hold the moment still. You can only be in it while it moves.",
  "What you practice in your head, you get good at. Be careful what you rehearse.",
  "Every plan is a guess about a stranger's life — the stranger being you, next month.",
  "The present asks almost nothing of you. Only that you show up for it.",
  "You've been to the future a thousand times in your mind, and it was never once accurate.",
  "Someday is not a day of the week.",
  "The clock is not chasing you. It's counting, the way it counts for everyone, evenly.",
  "You are not running late for your life. You're in it. This is it.",
  "Memory is a museum where you are also the curator, and the exhibits change overnight.",
  "Stop bracing. The thing you're bracing for isn't here, and the bracing is happening to your actual shoulders, now.",
  "A day is roughly a thousand small chances to be where you are.",
  "The future is a room you decorate and never enter.",
  "You're not too late and you're not early. Nobody is. There is only the present, and everyone is in it.",
  "The life you're planning and the life you're living are two different lives. Only one of them is real.",
  "When you get there, you'll be here again. \"Here\" is the only address you've ever had.",
  "That worry has been on a loop for an hour and hasn't solved anything. It isn't working. It never was.",
  "Notice your hands. Notice the light. That's not a technique. That's just where you are.",
  "You keep saying \"once things settle down.\" Things don't settle down. They change into different things.",
  "The past is closed. The future is imaginary. That leaves one door, and it's open.",
  "You will miss this ordinary morning. You could just have it instead.",
  "Attention is love with the sentiment stripped out. Where you put it is what you love.",
  "The moment doesn't have to be special to be the only one you have.",
  "Everything urgent will still be urgent in five minutes. Take the five minutes.",
  "You're not here to get through the day. The day isn't in your way.",
  "The future you're saving yourself for does not exist, and never will in the form you're picturing.",
  "Whatever you're doing, you're doing it with your one life. Even this. Even now.",
  "Tomorrow is a rumor.",
  "You already have the thing you keep saying you want to get back to. It's called being alive, and you're doing it.",
  "Rehearsing the worst case doesn't prevent it. It just makes you live it twice.",
  "The present moment is not a hallway. Stop walking through it to get somewhere else.",
  "Time isn't running out so much as simply running. You're in the current, not on the bank.",
  "You have been \"almost there\" your whole life. There is no there. There's here, again and again, and it's enough.",
  "What if nothing is missing.",
  "The day doesn't owe you meaning. Show up, and it tends to hand some over anyway.",
  "You spent the sunset photographing the sunset.",
  "The voice that says \"not yet\" will still be saying it on the last day. Overrule it.",
  "Being here is a skill. You get better at it the way you get better at anything: by returning after you drift.",
  "Your future self cannot enjoy the coffee. Only you, holding it, right now, can do that.",
  "The past feels solid because it's finished. The present feels unsteady because it's alive. Choose the unsteady one.",
  "There is no dress rehearsal and no understudy. It's you, tonight, live.",
  "If you're waiting for permission to be present, this is it.",
];
