// The writing. One string per piece. Plain text, 2–3 sentences.
// Order here does not matter — selection.js shuffles deterministically.
// To add more: append to the array. Nothing else to change.
//
// Structure: the past can't be improved, the future isn't the version in your
// head — which is freedom to move. Each piece lands on one generative forward
// action. Not guilt, not errands, not mindfulness.

export const PIECES = [
  "Nothing that happened this year rules out what you do this afternoon. The thing you've been building is closer than it feels. Put an hour in.",
  "You know the next move. It's small, it's obvious, it's available right now. Make it.",
  "Regret doesn't reach the past. Worry doesn't reach the future. Your effort only connects to one of the three, and you're standing in it.",
  "The past can't be improved and the future can't be rushed. The work in front of you moves forward by exactly one step. Take it.",
  "You're not starting from zero. You're starting from wherever the last real push left off. Pick it back up.",
  "Momentum doesn't come from the past or the plan. It comes from the next thing you actually do. Do one.",
  "The version in your head isn't the one that gets made. The one you put your hands on today is. Put your hands on it.",
  "There's a thread you dropped a while back that's still worth pulling. Pull it now, while you're thinking about it.",
  "Whatever you didn't get to last week is still gettable. Open it and do the first ten minutes.",
  "The plan is as good as it's going to get on paper. It gets better by being started. Start it.",
  "You've been thinking about it instead of doing it, and the thinking has run out of road. Do the first real part.",
  "What you got done yesterday is done and it counts. What you get done tomorrow depends on now. Move the current thing one step.",
  "The idea has survived every day you doubted it. That's a good sign. Give it the next hour.",
  "Nothing you rehearse in your head gets easier by rehearsal. It gets easier by one real attempt. Make the attempt.",
  "The future you keep planning for is built out of ordinary hours. This is one of them. Spend it on the thing.",
  "You don't need the whole day. You need the next thirty minutes pointed at one thing. Point them.",
  "The last version you made was a step. The next one is another step. Take it while the work is still warm.",
  "What's behind you taught you what you know. What's ahead is unwritten. Build a piece of it in the next hour.",
  "You keep waiting to feel ready. Ready shows up after you start, not before. Start.",
  "The work doesn't care that you're behind. It responds to being worked on. Work on it.",
  "Half-finished is closer to finished than not-started, and you're half-finished. Do the next part.",
  "The person who finishes this is the one sitting here now. There's no better-equipped version coming. Begin.",
  "The next step is smaller than things you've already done. Do it.",
  "Every good stretch of work you've had started with one unglamorous first move. Make the unglamorous first move.",
  "The doubt isn't new information. It shows up every time and it's been wrong before. Do the thing anyway.",
  "Right now you have it loaded — where you left off, what's next. That fades by tonight. Use it now.",
  "The plan can be refined forever. It gets real the first time you act on a line of it. Act on one.",
  "You're one focused hour from real progress, same as yesterday. The only difference is whether you spend it.",
  "Nothing about next week gets handled in advance. It gets handled a day at a time, starting today. Handle today's piece.",
  "Discipline is just starting before you feel like it. Start.",
  "You know more than you did last time you sat down with this. Sit down with it again and use what you learned.",
  "The gap between wanting to do it and doing it is about two minutes of friction. Push through the two minutes.",
  "The go-ahead you're waiting on has to come from you, today. Give it.",
  "The good work happens in the boring middle, and you're in the boring middle. Keep going.",
  "You can't out-plan the part where you actually do it. Do a chunk of it now.",
  "Whatever's stopping you now was there an hour ago, and you're still here. Push past it and do the next part.",
  "The next hour is the only one you get to decide about right now. Point it at what matters.",
  "It doesn't need a fresh start. It needs the next part done. Do it.",
  "Progress isn't waiting for a better week. It's available in the next forty minutes. Take them.",
  "You already know which task actually matters today. Start there.",
  "The future rewards what you do now, not what you worry about now. Trade the worry for twenty minutes of work.",
  "Whatever shape the day's taken so far, the rest of it is still yours to aim. Aim it.",
  "You don't have to finish it today. You have to move it today. Move it.",
  "The clearest thinking you'll do about this happens while you're doing it, not before. Get in.",
  "Small and now beats big and later, every time, because later doesn't show up. Do the small thing now.",
  "The last person to touch this project was you, and you left notes. Follow your own notes forward.",
  "There's a first sentence, a first call, a first line — whatever the first thing is, it's tiny. Do the tiny first thing.",
  "You're not blocked. You're between the deciding and the doing, and that gap closes from your side. Close it.",
  "The work you do in the next hour is the only part of tomorrow you actually control. Do it well.",
  "Every reason to wait is about a future that isn't here to confirm it. Move on the reason to start, which is here.",
  "The thing that felt impossible last month is smaller now, because you've been near it a while. Land on it.",
  "What you build this afternoon compounds. What you worry about this afternoon doesn't. Build.",
  "You don't need a plan for the whole thing. You need the next action, and you have it. Take it.",
  "Whatever you didn't do yesterday, yesterday's closed on it. Today's open. Put something in.",
  "The idea doesn't get more valid by aging. It gets real by being acted on. Act.",
  "You're closer to the finish than the start. That's not a reason to coast. Push.",
  "Nothing about the last hour has to define the next one. Reset and do one solid thing.",
  "You keep sharpening the tools. The tools are sharp. Cut something.",
  "The friction is highest right before you start and drops fast after. Get to after.",
  "Right now the whole project fits in your head. Do the part that's clearest before it gets fuzzy again.",
  "This isn't the first time you've come back to it. Make this the time you move it forward.",
  "Two things can't be worked on: what already happened, and what hasn't yet. That leaves the one in front of you.",
  "The energy you're spending bracing for later would move the current thing a real distance. Redirect it.",
  "Whatever you make of this year, you make it in weeks like this and hours like this. Start this hour's share.",
  "You have a clear next step and a slightly uncomfortable feeling about doing it. That's the normal state. Proceed.",
  "The plan survives contact with reality better than you expect. Give it some contact.",
  "Nothing gets un-hard by being postponed. It gets done by being started while it's still hard. Start.",
  "You know what progress would look like today. It's one specific thing. Go do the specific thing.",
  "The past version of you got you here. The future one can't help from there. The current one can. Get to work.",
  "What you're avoiding is usually the thing that would move it most. Do that one.",
  "You've got the next move already picked. The picking is done. Do it.",
  "The rough version you can make today beats the perfect one you're planning. Make the rough version.",
  "Whatever you're waiting for a sign about, the sign isn't in next week. Decide, and put twenty minutes toward it now.",
  "You came back to this on purpose. Don't just visit it — move it a step and then go.",
  "The hour's already running whether you use it or not. Aim it at the one thing that matters and go.",
];
